apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: static-client
spec:
  selector:
    app: static-client
  ports:
    - port: 80
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      name: static-client
      labels:
        app: static-client
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: static-client
          image: 'nicholasjackson/fake-service:v0.25.1'
          ports:
            - containerPort: 9090
              name: http
          env:
            - name: UPSTREAM_URIS
              value: "http://static-server"
      # If ACLs are enabled, the serviceAccountName must match the Consul service name.
      serviceAccountName: static-client
